license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/shipping-box"
iconFile="logo.png"
authors="ChinaEX123"
description='''
Add a shipping box for exchanging items.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ecliptic-seasons"
    type="optional"
    reason="Add seasonal selling rules."
    versionRange="[0.12,)"
    ordering="AFTER"
    side="BOTH"